### ISSUE TITLE
[Projeto] Desenhar telas do app

### ISSUE THREAD

**Issue by GuilhermeRoque** [best-software-company/docs#6]
- [x] Login
- [x] Registro
- [x] Inicial/Tarefas
- [x] Perfil
- [x] Ver Casa
- [x] Ver Perfil
- [x] Editar perfil
- [x] Cadastrar/Editar Casa
- [x] Regras
- [x] Criar/Editar Tarefa
- [x] Rotinas
- [x] Criar/Editar Rotina
- [x] Menu

**Comment by luizaalves** [comment]
[Prototipagem das telas.](https://github.com/best-software-company/docs/blob/master/markdown/Telas-do-app.md)
